name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Läuft jeden Tag um Mitternacht UTC
  workflow_dispatch:  # Manuelles Triggern

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Sync Fork
        uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: erincatto
          repo: box2d
          merge_method: rebase
